### ISSUE TITLE
No way to go back from searches

### ISSUE THREAD

**Issue by snstj** [fymmit/photo-gallery#41]
When entering tags from a picture info screen, you can't return to the main menu by pressing header etc. Only by doing another search or reloading the whole page. Same problem when doing a normal search.

**Comment by fymmit** [comment]
Working as intented. Intended way might be needing some tuning.

**Comment by snstj** [comment]
Shame because it's annoying as hell.

**Comment by fymmit** [comment]
Oh I actually implemented this. Oopsie!
